services:
  frc-codex-server:
    image: frc-codex-server:latest
    depends_on:
      localstack:
        condition: service_healthy
    healthcheck:
      interval: 2s
      retries: 30
      test: curl localhost:8080/health --fail || exit 1
      timeout: 2s
    environment:
      AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID"
      AWS_HOST: "http://localstack.localhost:4566"
      AWS_REGION: "eu-west-2"
      AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
      COMPANIES_HOUSE_DOCUMENT_API_BASE_URL: "https://document-api.companieshouse.gov.uk"
      COMPANIES_HOUSE_INFORMATION_API_BASE_URL: "https://api.companieshouse.gov.uk"
      COMPANIES_HOUSE_STREAM_API_BASE_URL: "https://stream.companieshouse.gov.uk"
      DB_PASSWORD: "frc_codex"
      DB_URL: "jdbc:postgresql://postgres.localhost:5432/frc_codex"
      DB_USERNAME: "frc_codex"
      FCA_DATA_API_BASE_URL: "https://data.fca.org.uk/artefacts/"
      FCA_SEARCH_API_URL: "https://api.data.fca.org.uk/search?index=fca-nsm-searchdata"
      SQS_JOBS_QUEUE_NAME: "frc_codex_jobs"
      SQS_RESULTS_QUEUE_NAME: "frc_codex_results"
    secrets:
      - frc-codex-server.secrets
    ports:
      - 8080:8080
  frc-codex-processor:
    image: frc-codex-processor:latest
    depends_on:
      localstack:
        condition: service_healthy
    healthcheck:
      interval: 1s
      retries: 0
      test: exit 0 # TODO: Improve healthcheck
      timeout: 1s
    environment:
      MAXIMUM_PROCESSORS: '4'
      SECRETS_FILEPATH: '/run/secrets/frc-codex-server.secrets'
      SQS_ENDPOINT_URL: 'http://localstack.localhost:4566'
      SQS_REGION_NAME: 'eu-west-2'
      S3_ENDPOINT_URL: 'http://localstack.localhost:4566'
      S3_HTTP_CACHE_BUCKET_NAME: 'frc-codex-http-cache'
      S3_RESULTS_BUCKET_NAME: 'frc-codex-results'
      S3_REGION_NAME: 'eu-west-2'
      SQS_JOBS_QUEUE_NAME: 'frc_codex_jobs'
      SQS_RESULTS_QUEUE_NAME: 'frc_codex_results'
    secrets:
      - frc-codex-server.secrets
    volumes:
      - ../tmp:/tmp
  localstack:
    image: localstack/localstack:3.4.0
    healthcheck:
      interval: 10s
      retries: 15
      test: curl localstack:4566/health || exit 1
      timeout: 4s
    environment:
      S3_HTTP_CACHE_BUCKET_NAME: 'frc-codex-http-cache'
      S3_RESULTS_BUCKET_NAME: 'frc-codex-results'
      S3_REGION_NAME: "eu-west-2"
      SQS_REGION_NAME: "eu-west-2"
    ports:
      - 4566:4566
    networks:
      default:
        aliases:
          - localstack.localhost
    volumes:
      - ./localstack.sh:/etc/localstack/init/ready.d/script.sh
  postgres:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    environment:
      POSTGRES_DB: frc_codex
      POSTGRES_USER: frc_codex
      POSTGRES_PASSWORD: frc_codex
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - postgres.localhost
secrets:
  frc-codex-server.secrets:
    file: ../frc-codex-server.secrets
