services:
  frc-codex-server:
    image: frc-codex-server:latest
    depends_on:
      localstack:
        condition: service_healthy
    healthcheck:
      interval: 2s
      retries: 5
      test: curl localhost:8080/health --fail || exit 1
      timeout: 2s
    environment:
      COMPANIES_HOUSE_DOCUMENT_API_BASE_URL: "https://document-api.companieshouse.gov.uk"
      COMPANIES_HOUSE_INFORMATION_API_BASE_URL: "https://api.companieshouse.gov.uk"
      COMPANIES_HOUSE_STREAM_API_BASE_URL: "https://stream.companieshouse.gov.uk"
    secrets:
      - frc-codex-server.secrets
    ports:
      - 8080:8080
  frc-codex-processor:
    image: frc-codex-processor:latest
    depends_on:
      localstack:
        condition: service_healthy
    healthcheck:
      interval: 1s
      retries: 0
      test: exit 0 # TODO: Improve healthcheck
      timeout: 1s
    environment:
      SQS_ENDPOINT_URL: 'http://localstack.localhost:4566'
      SQS_QUEUE_NAME: 'frc_codex_processor_queue'
      SQS_REGION_NAME: 'eu-west-2'
  localstack:
    image: localstack/localstack:3.4.0
    healthcheck:
      interval: 10s
      retries: 15
      test: curl localstack:4566/health || exit 1
      timeout: 4s
    environment:
      SERVICES: sqs
      DEBUG: 1
    ports:
      - "4566:4566"
    networks:
      default:
        aliases:
          - localstack.localhost
secrets:
  frc-codex-server.secrets:
    file: ../frc-codex-server.secrets
