name: Build Server
description: Builds the frc-codex-server Docker image

runs:
  using: composite
  steps:
    - uses: docker/setup-buildx-action@v3.8.0
    - name: Build frc-codex-server image
      uses: docker/build-push-action@v6.10.0
      with:
        context: .
        file: frc-codex-server.Dockerfile
        push: false
        tags: frc-codex-server
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/frc-codex-server.tar
