name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"

jobs:
  build-processor:
    uses: ./.github/workflows/build-processor.yml

  build-server:
    uses: ./.github/workflows/build-server.yml

  test:
    needs: [build-processor, build-server]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download processor
        uses: actions/download-artifact@v4
        with:
          name: frc-codex-processor
          path: /tmp
      - name: Load processor
        run: |
          docker load --input /tmp/frc-codex-processor.tar
          docker image ls -a  

      - name: Download server
        uses: actions/download-artifact@v4
        with:
          name: frc-codex-server
          path: /tmp
      - name: Load server
        run: |
          docker load --input /tmp/frc-codex-server.tar
          docker image ls -a  

      - name: "Compose"
        timeout-minutes: 5
        shell: bash
        run: |
          ./dev/env-compose.sh
      - name: "Test"
        shell: bash
        run: |
          curl -i --fail http://localhost:8080/
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docker-logs
          path: ./dev/logs
