name: Build Processor

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-processor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build frc-codex-processor image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: frc-codex-processor.Dockerfile
          push: false
          tags: frc-codex-processor
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/frc-codex-processor.tar
      - uses: actions/upload-artifact@v4
        with:
          name: frc-codex-processor
          path: /tmp/frc-codex-processor.tar
