name: Build Server

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build frc-codex-server image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: frc-codex-server.Dockerfile
          push: false
          tags: frc-codex-server
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/frc-codex-server.tar
      - uses: actions/upload-artifact@v4
        with:
          name: frc-codex-server
          path: /tmp/frc-codex-server.tar
