name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build frc-codex-processor image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: frc-codex-processor.Dockerfile
          push: false
          tags: frc-codex-processor
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
      - name: Build frc-codex-server image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: frc-codex-server.Dockerfile
          push: false
          tags: frc-codex-server
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
      - name: "Compose"
        timeout-minutes: 3
        shell: bash
        run: |
          ./dev/env-setup.sh
