name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Compose"
        timeout-minutes: 3
        shell: bash
        run: |
          ./dev/env-setup.sh
