name: Build Processor

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-processor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
          check-latest: true
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
      - uses: docker/setup-buildx-action@v3
      - name: Build frc-codex-processor image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: frc-codex-processor.Dockerfile
          push: false
          tags: frc-codex-processor
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/frc-codex-processor.tar
      - uses: actions/upload-artifact@v4
        with:
          name: frc-codex-processor
          path: /tmp/frc-codex-processor.tar
