name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Secrets"
        shell: bash
        run: |
          echo "COMPANIES_HOUSE_REST_API_KEY=${{ secrets.COMPANIES_HOUSE_REST_API_KEY }}" >> ./frc-codex-server.secrets
          echo "COMPANIES_HOUSE_STREAM_API_KEY=${{ secrets.COMPANIES_HOUSE_STREAM_API_KEY }}" >> ./frc-codex-server.secrets
      - name: "Compose"
        timeout-minutes: 5
        shell: bash
        run: |
          ./dev/env-setup.sh
      - name: "Test"
        # dependabot can not access secrets, which is required for these tests to pass
        # Quick workaround is to not run the tests, but we could implement solutions described here:
        # https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-797125425
        if: ${{ github.actor != 'dependabot[bot]' }}
        shell: bash
        run: |
          sleep 60
          curl -i --fail http://localhost:8080/
          curl -i --fail http://localhost:8080/admin/smoketest/companieshouse/company/00324341
          curl -i --fail http://localhost:8080/admin/smoketest/fca
          curl -i --fail http://localhost:8080/admin/smoketest/indexer
          curl -i --fail http://localhost:8080/admin/smoketest/queue
          curl -i --fail http://localhost:8080/admin/smoketest/database

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docker-logs
          path: ./dev/logs
