name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"

jobs:
  build-processor:
    uses: ./.github/workflows/build-processor.yml

  build-server:
    uses: ./.github/workflows/build-server.yml

  test:
    needs: [build-processor, build-server]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download processor
        uses: actions/download-artifact@v4
        with:
          name: frc-codex-processor
          path: /tmp
      - name: Load processor
        run: |
          docker load --input /tmp/frc-codex-processor.tar
          docker image ls -a  

      - name: Download server
        uses: actions/download-artifact@v4
        with:
          name: frc-codex-server
          path: /tmp
      - name: Load server
        run: |
          docker load --input /tmp/frc-codex-server.tar
          docker image ls -a  

      - name: "Secrets"
        shell: bash
        run: |
          echo "COMPANIES_HOUSE_REST_API_KEY=${{ secrets.COMPANIES_HOUSE_REST_API_KEY }}" >> ./frc-codex-server.secrets
          echo "COMPANIES_HOUSE_STREAM_API_KEY=${{ secrets.COMPANIES_HOUSE_STREAM_API_KEY }}" >> ./frc-codex-server.secrets
      - name: "Compose"
        timeout-minutes: 5
        shell: bash
        run: |
          ./dev/env-compose.sh
      - name: "Test"
        # dependabot can not access secrets, which is required for these tests to pass
        # Quick workaround is to not run the tests, but we could implement solutions described here:
        # https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-797125425
        if: ${{ github.actor != 'dependabot[bot]' }}
        shell: bash
        run: |
          curl -i --fail http://localhost:8080/
          curl -i --fail http://localhost:8080/admin/smoketest/companieshouse/company/00324341
          curl -i --fail -X POST http://localhost:8080/admin/smoketest/database \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "registryCode=reg1&downloadUrl=dl1"
          curl -i --fail http://localhost:8080/admin/smoketest/fca
          sleep 30
          curl -i --fail http://localhost:8080/admin/smoketest/indexer
          curl -i --fail http://localhost:8080/admin/smoketest/queue

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docker-logs
          path: ./dev/logs
